---
- hosts: all
  vars:
    project_path: /home/ubuntu/node-app/node_modules/movie-analyst-api

  tasks:

    - name: Install the nodejs LTS repos
      become: true
      apt_repository:
        repo: "deb http://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install NodeJs
      become: true
      apt:
        name: nodejs
        state: present
    
    - name: Install PM2
      become: true
      npm: name=pm2 global=yes state=present

    - name: Installing the app
      become: true
      npm:
        path: {{ current_path }}

    - name: Delete old pm2 process
      command: pm2 delete ws-node
      ignore_errors: yes

    - name: Start pm2
      command: pm2 start /home/ubuntu/node-app/node_modules/movie-analyst-api/server.js --name node-app
