---
- hosts: all
  vars:
    project_path: /home/ubuntu/node-app/node_modules/movie-analyst-api

  tasks:

    - name: Install the gpg key for nodejs LTS
      become: true
      apt_key:
        url: "http://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
        validate_certs: no

    - name: Install the nodejs LTS repos
      become: true
      apt_repository:
        repo: "deb http://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install NodeJs
      become: true
      apt:
        name: nodejs
        state: present
    
    - name: Install PM2
      become: true
      npm: name=pm2 global=yes state=present
    
    - name: Install APP tar
      become: true
      chdir: {{project_path}}
      command: npm install movie-analyst-api-1.0.0.tgz -f

    - name: Listing files node-app
      become: true
      command: ls -l {{ current_path }}

    - name: Installing the app
      become: true
      npm:
        path: {{ current_path }}

    - name: Delete old pm2 process
      command: pm2 delete ws-node
      ignore_errors: yes

    - name: Start pm2
      command: pm2 start {{ current_path }}/server.js --name node-app
